### ISSUE TITLE
Find a js lib for select files from local

### ISSUE THREAD

**Issue by yihangx** [cytoscape/js4cytoscape#15]
Since app commands support install app from file, we should find a js library to select files from local in the web page, and the argument for app commands should be the selected file location.

**Comment by yihangx** [comment]
@AlexanderPico I did some research on this. The command 'apps install' asks the full path of the jar file. But in JavaScript, it is impossible to get full path of a file because of the security reason.

**Comment by AlexanderPico** [comment]
Wow. You're correct. I had to test this myself to convince myself :)

Interestingly, all FF does is *insert* a fakepath into the actual full path:
```
Failed reading session file: /Applications/Cytoscape_v3.9.1/C:\fakepath\galFiltered.cys
```

Technically, this "obscured" path is easy to parse into a real path, but this would clearly break the intention of the security and likely not work cross browsers, nor in future updates.

**Comment by AlexanderPico** [comment]
Ok. So, I'm convinced we need to make "Install from file..."  a Java Swing menu item that is completely separate from the App Manager work we are doing in JS.
